export const CREATE_DESK = 'CREATE_DESK'
export const UPDATE_DESK = 'UPDATE_DESK'
export const FETCH_PLANS = 'FETCH_PLANS'
export const SELECT_FLOOR = 'SELECT_FLOOR'
export const SELECT_DESK = 'SELECT_DESK'
export const DESELECT_DESK = 'DESELECT_DESK'
